import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar  from "../components/navbar";
import { Nunito } from "next/font/google";
import { Raleway } from 'next/font/google';
const nunito = Nunito({
  subsets: ["latin"],
  display: "fallback", // <--
});
const inter = Inter({ subsets: ["latin"] });
const raleway = Raleway({
  subsets: ['latin', 'latin-ext', 'vietnamese'],
 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
